name: Weekly Research Digest

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    inputs:
      window_days:
        description: 'Days window to search'
        required: false
        default: '7'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate config
        run: |
          if [ ! -f config.yaml ]; then
            cp config.example.yaml config.yaml
          fi
          if [ -n "${{ github.event.inputs.window_days }}" ]; then
            python - <<'PY'
import yaml
from pathlib import Path
cfg = yaml.safe_load(Path('config.yaml').read_text())
cfg['sources']['arxiv']['window_days'] = int('${{ github.event.inputs.window_days }}')
Path('config.yaml').write_text(yaml.safe_dump(cfg, allow_unicode=True, sort_keys=False))
print('Updated window_days to', cfg['sources']['arxiv']['window_days'])
PY
          fi

      - name: Run digest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
        run: |
          python -m digest.main --config config.yaml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest
          path: out/*

      - name: Commit report to repo
        run: |
          if [ -d out ] && [ "$(ls -A out)" ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            mkdir -p reports
            ts=$(date -u +"%Y-%m-%d")
            dest="reports/${ts}"
            mkdir -p "$dest"
            cp -r out/* "$dest"/
            git add reports || true
            git commit -m "Add weekly digest ${ts}" || echo "No changes to commit"
            git push || echo "No push"
          else
            echo "No reports generated"
          fi
